#!/usr/bin/python3

import sys

from PyQt5.QtWidgets import QApplication
from PyQt5.QtWebEngineWidgets import QWebEngineProfile
from PyQt5.QtWebEngineCore import QWebEngineUrlRequestInterceptor
from BrowserWindow import BrowserWindow

import dbus, dbus.service
from dbus.mainloop.pyqt5 import DBusQtMainLoop

class Interceptor(QWebEngineUrlRequestInterceptor):

    def __init__(self, svc):
        super().__init__()
        self.svc = svc

    def interceptRequest(self, info):
        # TODO: how to delete referer here?
        print(info.firstPartyUrl(), "->", info.requestUrl().toString(), info.resourceType())


class BrowserService(dbus.service.Object):
    def __init__(self):
        bus_name = dbus.service.BusName('eu.waldteufel.Shower1', bus=dbus.SessionBus())
        super().__init__(object_path='/shower', bus_name=bus_name)

        self.interceptor = Interceptor(self)
        pr = QWebEngineProfile.defaultProfile()
        pr.setRequestInterceptor(self.interceptor)

    @dbus.service.method('eu.waldteufel.Shower1', in_signature='s', out_signature='i')
    def open(self, url):
        BrowserWindow(self, url).show()
        return 0


if __name__ == '__main__':
    DBusQtMainLoop(set_as_default=True)
    qApp = QApplication(sys.argv)
    qApp.applicationName = 'shower'

    BrowserService()

    res = 1
    try:
        res = qApp.exec_()
    finally:
        del qApp
    sys.exit(res)
