#!/usr/bin/python3

import sys

from PyQt5.QtWidgets import QApplication
from BrowserWindow import BrowserWindow

import dbus, dbus.service
from dbus.mainloop.pyqt5 import DBusQtMainLoop


class BrowserService(dbus.service.Object):
    def __init__(self):
        busName = dbus.service.BusName('eu.waldteufel.Shower1', bus=dbus.SessionBus())
        dbus.service.Object.__init__(self, busName, '/shower')

    @dbus.service.method('eu.waldteufel.Shower1', in_signature='s', out_signature='i')
    def open(self, url):
        BrowserWindow(url).show()
        return 0


if __name__ == '__main__':
    DBusQtMainLoop(set_as_default=True)
    qApp = QApplication(sys.argv)

    BrowserService()

    res = 1
    try:
        res = qApp.exec_()
    finally:
        del qApp
    sys.exit(res)
